services:
  - type: cron
    name: resybot-4charles
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: python -m resybot -c config.yaml --no-wait --restaurant "4 Charles Prime Rib"
    schedule: "58 12 * * *"  # 8:58 AM ET (UTC-4), bot waits for exact 9:00:00
    envVars:
      - key: TZ
        value: America/New_York

  - type: cron
    name: resybot-has-snack-bar
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: python -m resybot -c config.yaml --no-wait --restaurant "Ha's Snack Bar"
    schedule: "57 15 * * *"  # 11:57 AM ET (UTC-4)
    envVars:
      - key: TZ
        value: America/New_York

  - type: cron
    name: resybot-odo
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: python -m resybot -c config.yaml --no-wait --restaurant "Odo East Village"
    schedule: "57 3 * * *"   # 11:57 PM ET (UTC-4)
    envVars:
      - key: TZ
        value: America/New_York
